[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
memepool = "2FFxe3uuZcEoKEdtotrANZmYQZxiaqAoZC6afxYFTWoz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/memepool.ts"
