[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
memepool = "4DkcsX8ypqXChJvqUTyVdtL9463KyTT3RBEUHLkTM6Ls"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/memepool.ts"
